language: python
env:
  Z3_VERSION: 4.6.0
  UBUNTU_VERSION: 16.04

## DOCKER
#services:
#  docker
#script:
#  - echo "COMPILING"
#  - ./ci-helpers/solc-wrapper contracts/useless.sol
#  - ./ci-helpers/solc-wrapper contracts/compilation_fail.sol
#  - echo "STATIC ANALYSIS"
#  - ./ci-helpers/oyente-wrapper contracts/compilation_fail.sol

## FULL INSTALL
before_install:
  - add-apt-repository -y ppa:ethereum/ethereum
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
#  - apt update -y
  - apt install -y wget
  - python -m virtualenv env
  - . env/bin/activate
  - wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/z3-${Z3_VERSION}-x64-ubuntu-${UBUNTU_VERSION}.zip
install:
  - apt install -y ethereum solc nodejs
  - python -m pip install oyente
  - unzip z3-${Z3_VERSION}-x64-ubuntu-${UBUNTU_VERSION}.zip -d /tmp/
  - cp -ar /tmp/z3-${Z3_VERSION}-x64-ubuntu-${UBUNTU_VERSION}/{bin,include} /usr/local/
  - npm install -g solium solhint
script:
  - echo "COOOOL"
  - ls -l