[package]
name = "solsa"
version = "0.1.0"
authors = ["Filipe Gonçalves <filipe@impossible.com>"]

[dependencies]
clap = "2.31"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "0.11"
lazy_static = "1.0.1"